version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: server123*
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://myuser:server123*@db:5432/mydb
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  pgdata:
